### ISSUE TITLE
RFE for README

### ISSUE THREAD

**Issue by apinnick** [Lennonka/refactordoc#1]
You might want to consider adding a paragraph explaining what the script does, for those of us who are not familiar with the term "refactoring". I looked at the examples and I'm still not sure. Does it rename a file to match its title?

**Comment by Lennonka** [comment]
[Better?](https://github.com/Lennonka/refactordoc/blob/main/README.md#refactordoc)

**Comment by apinnick** [comment]
Yes, that's much clearer. Thanks!
